#Consolidando arquivos

In [1]:
import pandas as pd
import os
import time

In [2]:
Data_Hoje = time.strftime("%d-%m-%Y")
print(f"Data de hoje: {Data_Hoje}")

Data de hoje: 15-08-2025

In [3]:
vendas2021 = pd.read_excel(r"C:\Aplicativos\Meus_Arquivos_Willian\Ambiente_Desenvolvimento\Arquivos_in\Vendas\Vendas2021.xlsx")
vendas2022 = pd.read_excel(r"C:\Aplicativos\Meus_Arquivos_Willian\Ambiente_Desenvolvimento\Arquivos_in\Vendas\Vendas2022.xlsx")
vendas2023 = pd.read_excel(r"C:\Aplicativos\Meus_Arquivos_Willian\Ambiente_Desenvolvimento\Arquivos_in\Vendas\Vendas2023.xlsx")

In [4]:
vendas2021.head()

,Data,Id Venda,IdCategoria,Categoria,IdPais,Pais,idProduto,Produto,Custo fabricacao,Unidades Vendidas,Preco venda,Vendas total,Descontos
0,2021-04-02,573,1,Moda,636,Alemanha,15,Shorts,10,1178,20,23560,3674.400
1,2021-04-02,599,4,Acessórios,637,França,12,Relogio,120,930,15,13950,7795.125
2,2021-04-02,1125,1,Moda,636,Alemanha,15,Shorts,10,583,20,11660,3674.400
3,2021-04-02,1151,4,Acessórios,637,França,12,Relogio,120,548,15,8220,7795.125
4,2021-04-06,394,5,Automitivos,639,USA,8,Limpa vidros,250,503,300,150900,19392.000

In [5]:
vendas2022.head()

,Data,Id Venda,IdCategoria,Categoria,IdPais,Pais,idProduto,Produto,Custo fabricacao,Unidades Vendidas,Preco venda,Vendas total,Descontos
0,2022-12-30,267,1,Moda,639,USA,15,Shorts,250,701,7,4907,199.5
1,2022-12-30,819,1,Moda,639,USA,15,Shorts,250,677,7,4739,199.5
2,2022-12-29,120,4,Acessórios,639,USA,12,Relogio,10,81,15,1215,577.5
3,2022-12-29,160,3,Eletrônicos,636,Alemanha,9,Notebook,10,481,125,60125,5887.5
4,2022-12-29,712,3,Eletrônicos,636,Alemanha,9,Notebook,10,784,125,98000,5887.5

In [6]:
vendas2023.head()

,Data,Id Venda,IdCategoria,Categoria,IdPais,Pais,idProduto,Produto,Custo fabricacao,Unidades Vendidas,Preco venda,Vendas total,Descontos
0,2023-04-02,573,1,Moda,636,Alemanha,15,Shorts,10,1033,20,20660,3674.400
1,2023-04-02,599,4,Acessórios,637,França,12,Relogio,120,739,15,11085,7795.125
2,2023-04-02,1125,1,Moda,636,Alemanha,15,Shorts,10,790,20,15800,3674.400
3,2023-04-02,1151,4,Acessórios,637,França,12,Relogio,120,953,15,14295,7795.125
4,2023-04-06,394,5,Automitivos,639,USA,8,Limpa vidros,250,290,300,87000,19392.000

Consolidando arquivos de uma pasta

In [7]:
#Diretório onde estão os arquivos
diretorio = r"C:\Aplicativos\Meus_Arquivos_Willian\Ambiente_Desenvolvimento\Arquivos_in\Backups"

#Lista os arquivos do diretório
arquivos = []

#Iterar sobre os arquivos no diretório
for arquivo in os.listdir(diretorio):                        #lista os arquivos no diretório
    if arquivo.endswith(".xlsx"):                            #Verifica se o arquivo é um Excel
        caminho_completo = os.path.join(diretorio, arquivo)  #Cria o caminho completo do arquivo
        df = pd.read_excel(caminho_completo)                 #Lê o arquivo Excel
        arquivos.append(df)                                  #Adiciona o DataFrame à lista 1 a 1
#Consolidar os DataFrames em um único DataFrame
consolidado = pd.concat(arquivos, ignore_index=True)
consolidado.head(100)

,Data,Id Venda,IdCategoria,Categoria,IdPais,Pais,idProduto,Produto,Custo fabricacao,Unidades Vendidas,Preco venda,Vendas total,Descontos
0,2021-04-02,573,1,Moda,636,Alemanha,15,Shorts,10,1178,20,23560,3674.400
1,2021-04-02,599,4,Acessórios,637,França,12,Relogio,120,930,15,13950,7795.125
2,2021-04-02,1125,1,Moda,636,Alemanha,15,Shorts,10,583,20,11660,3674.400
3,2021-04-02,1151,4,Acessórios,637,França,12,Relogio,120,548,15,8220,7795.125
4,2021-04-06,394,5,Automitivos,639,USA,8,Limpa vidros,250,503,300,150900,19392.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,2025-08-11,117,5,Automitivos,635,Canadá,10,Pneus,10,416,300,124800,11496.000
70,2025-08-11,557,1,Moda,638,México,5,Camiseta,10,305,20,6100,2959.200
71,2025-08-11,1109,1,Moda,638,México,5,Camiseta,10,1199,20,23980,2959.200
72,2025-08-11,1109,1,Moda,638,México,5,Camiseta,10,1199,20,23980,2959.200
73,2025-08-12,1109,1,Moda,638,México,5,Camiseta,10,1199,20,23980,2959.200

In [9]:
#Colacar a data de hoje no arquivo consolidado
consolidado['Dt_ingest'] = Data_Hoje
consolidado.head(20)

,Data,Id Venda,IdCategoria,Categoria,IdPais,Pais,idProduto,Produto,Custo fabricacao,Unidades Vendidas,Preco venda,Vendas total,Descontos,Dt_ingest
0,2021-04-02,573,1,Moda,636,Alemanha,15,Shorts,10,1178,20,23560,3674.400,15-08-2025
1,2021-04-02,599,4,Acessórios,637,França,12,Relogio,120,930,15,13950,7795.125,15-08-2025
2,2021-04-02,1125,1,Moda,636,Alemanha,15,Shorts,10,583,20,11660,3674.400,15-08-2025
3,2021-04-02,1151,4,Acessórios,637,França,12,Relogio,120,548,15,8220,7795.125,15-08-2025
4,2021-04-06,394,5,Automitivos,639,USA,8,Limpa vidros,250,503,300,150900,19392.000,15-08-2025
5,2021-04-06,946,5,Automitivos,639,USA,8,Limpa vidros,250,153,300,45900,19392.000,15-08-2025
6,2021-04-09,117,5,Automitivos,635,Canadá,10,Pneus,10,195,300,58500,11496.000,15-08-2025
7,2021-04-09,557,1,Moda,638,México,5,Camiseta,10,61,20,1220,2959.200,15-08-2025
8,2021-04-09,1109,1,Moda,638,México,5,Camiseta,10,1154,20,23080,2959.200,15-08-2025
9,2021-04-10,574,1,Moda,637,França,15,Shorts,250,313,7,2191,1252.440,15-08-2025
10,2021-04-10,690,4,Acessórios,636,Alemanha,2,Braceletes,250,512,15,7680,1107.000,15-08-2025
11,2021-04-10,1126,1,Moda,637,França,15,Shorts,250,164,7,1148,1252.440,15-08-2025
12,2021-04-10,1242,4,Acessórios,636,Alemanha,2,Braceletes,250,232,15,3480,1107.000,15-08-2025
13,2021-04-11,78,3,Eletrônicos,637,França,16,Smartfone,10,1194,125,149250,983.750,15-08-2025
14,2021-04-12,17,1,Moda,635,Canadá,3,Calça social,10,154,20,3080,0.000,15-08-2025
15,2021-04-12,208,4,Acessórios,638,México,2,Braceletes,250,947,15,14205,908.400,15-08-2025
16,2021-04-12,564,1,Moda,639,USA,15,Shorts,250,364,350,127400,41412.000,15-08-2025
17,2021-04-12,760,4,Acessórios,638,México,2,Braceletes,250,743,15,11145,908.400,15-08-2025
18,2022-12-30,267,1,Moda,639,USA,15,Shorts,250,701,7,4907,199.500,15-08-2025
19,2022-12-30,819,1,Moda,639,USA,15,Shorts,250,677,7,4739,199.500,15-08-2025

In [10]:
#Converte as data para formato de data
consolidado['Dt_ingest'] = pd.to_datetime(consolidado['Dt_ingest'], format='%d-%m-%Y')
consolidado['Data'] = pd.to_datetime(consolidado['Data'], format='%d-%m-%Y')

In [11]:
#tipos dos dados
print(consolidado.dtypes)

Data                 datetime64[ns]
Id Venda                      int64
IdCategoria                   int64
Categoria                    object
IdPais                        int64
Pais                         object
idProduto                     int64
Produto                      object
Custo fabricacao              int64
Unidades Vendidas             int64
Preco venda                   int64
Vendas total                  int64
Descontos                   float64
Dt_ingest            datetime64[ns]
dtype: object

In [12]:
#Subtrrair Dt_ingest da Data ver os dias de diferença
consolidado['Diferenca_Dias'] = (consolidado['Dt_ingest'] - consolidado['Data']).dt.days

In [13]:
consolidado.head(20)

,Data,Id Venda,IdCategoria,Categoria,IdPais,Pais,idProduto,Produto,Custo fabricacao,Unidades Vendidas,Preco venda,Vendas total,Descontos,Dt_ingest,Diferenca_Dias
0,2021-04-02,573,1,Moda,636,Alemanha,15,Shorts,10,1178,20,23560,3674.400,2025-08-15,1596
1,2021-04-02,599,4,Acessórios,637,França,12,Relogio,120,930,15,13950,7795.125,2025-08-15,1596
2,2021-04-02,1125,1,Moda,636,Alemanha,15,Shorts,10,583,20,11660,3674.400,2025-08-15,1596
3,2021-04-02,1151,4,Acessórios,637,França,12,Relogio,120,548,15,8220,7795.125,2025-08-15,1596
4,2021-04-06,394,5,Automitivos,639,USA,8,Limpa vidros,250,503,300,150900,19392.000,2025-08-15,1592
5,2021-04-06,946,5,Automitivos,639,USA,8,Limpa vidros,250,153,300,45900,19392.000,2025-08-15,1592
6,2021-04-09,117,5,Automitivos,635,Canadá,10,Pneus,10,195,300,58500,11496.000,2025-08-15,1589
7,2021-04-09,557,1,Moda,638,México,5,Camiseta,10,61,20,1220,2959.200,2025-08-15,1589
8,2021-04-09,1109,1,Moda,638,México,5,Camiseta,10,1154,20,23080,2959.200,2025-08-15,1589
9,2021-04-10,574,1,Moda,637,França,15,Shorts,250,313,7,2191,1252.440,2025-08-15,1588
10,2021-04-10,690,4,Acessórios,636,Alemanha,2,Braceletes,250,512,15,7680,1107.000,2025-08-15,1588
11,2021-04-10,1126,1,Moda,637,França,15,Shorts,250,164,7,1148,1252.440,2025-08-15,1588
12,2021-04-10,1242,4,Acessórios,636,Alemanha,2,Braceletes,250,232,15,3480,1107.000,2025-08-15,1588
13,2021-04-11,78,3,Eletrônicos,637,França,16,Smartfone,10,1194,125,149250,983.750,2025-08-15,1587
14,2021-04-12,17,1,Moda,635,Canadá,3,Calça social,10,154,20,3080,0.000,2025-08-15,1586
15,2021-04-12,208,4,Acessórios,638,México,2,Braceletes,250,947,15,14205,908.400,2025-08-15,1586
16,2021-04-12,564,1,Moda,639,USA,15,Shorts,250,364,350,127400,41412.000,2025-08-15,1586
17,2021-04-12,760,4,Acessórios,638,México,2,Braceletes,250,743,15,11145,908.400,2025-08-15,1586
18,2022-12-30,267,1,Moda,639,USA,15,Shorts,250,701,7,4907,199.500,2025-08-15,959
19,2022-12-30,819,1,Moda,639,USA,15,Shorts,250,677,7,4739,199.500,2025-08-15,959

In [14]:
# ver a diferença em meses
consolidado['Diferenca_Meses'] = (consolidado['Dt_ingest'] - consolidado['Data']).dt.days // 30

In [15]:
consolidado.head(20)

,Data,Id Venda,IdCategoria,Categoria,IdPais,Pais,idProduto,Produto,Custo fabricacao,Unidades Vendidas,Preco venda,Vendas total,Descontos,Dt_ingest,Diferenca_Dias,Diferenca_Meses
0,2021-04-02,573,1,Moda,636,Alemanha,15,Shorts,10,1178,20,23560,3674.400,2025-08-15,1596,53
1,2021-04-02,599,4,Acessórios,637,França,12,Relogio,120,930,15,13950,7795.125,2025-08-15,1596,53
2,2021-04-02,1125,1,Moda,636,Alemanha,15,Shorts,10,583,20,11660,3674.400,2025-08-15,1596,53
3,2021-04-02,1151,4,Acessórios,637,França,12,Relogio,120,548,15,8220,7795.125,2025-08-15,1596,53
4,2021-04-06,394,5,Automitivos,639,USA,8,Limpa vidros,250,503,300,150900,19392.000,2025-08-15,1592,53
5,2021-04-06,946,5,Automitivos,639,USA,8,Limpa vidros,250,153,300,45900,19392.000,2025-08-15,1592,53
6,2021-04-09,117,5,Automitivos,635,Canadá,10,Pneus,10,195,300,58500,11496.000,2025-08-15,1589,52
7,2021-04-09,557,1,Moda,638,México,5,Camiseta,10,61,20,1220,2959.200,2025-08-15,1589,52
8,2021-04-09,1109,1,Moda,638,México,5,Camiseta,10,1154,20,23080,2959.200,2025-08-15,1589,52
9,2021-04-10,574,1,Moda,637,França,15,Shorts,250,313,7,2191,1252.440,2025-08-15,1588,52
10,2021-04-10,690,4,Acessórios,636,Alemanha,2,Braceletes,250,512,15,7680,1107.000,2025-08-15,1588,52
11,2021-04-10,1126,1,Moda,637,França,15,Shorts,250,164,7,1148,1252.440,2025-08-15,1588,52
12,2021-04-10,1242,4,Acessórios,636,Alemanha,2,Braceletes,250,232,15,3480,1107.000,2025-08-15,1588,52
13,2021-04-11,78,3,Eletrônicos,637,França,16,Smartfone,10,1194,125,149250,983.750,2025-08-15,1587,52
14,2021-04-12,17,1,Moda,635,Canadá,3,Calça social,10,154,20,3080,0.000,2025-08-15,1586,52
15,2021-04-12,208,4,Acessórios,638,México,2,Braceletes,250,947,15,14205,908.400,2025-08-15,1586,52
16,2021-04-12,564,1,Moda,639,USA,15,Shorts,250,364,350,127400,41412.000,2025-08-15,1586,52
17,2021-04-12,760,4,Acessórios,638,México,2,Braceletes,250,743,15,11145,908.400,2025-08-15,1586,52
18,2022-12-30,267,1,Moda,639,USA,15,Shorts,250,701,7,4907,199.500,2025-08-15,959,31
19,2022-12-30,819,1,Moda,639,USA,15,Shorts,250,677,7,4739,199.500,2025-08-15,959,31

In [16]:
#ver a diferença em anos
consolidado['Diferenca_Ano'] = (consolidado['Dt_ingest'] - consolidado['Data']).dt.days // 365

In [17]:
consolidado.head(20)

,Data,Id Venda,IdCategoria,Categoria,IdPais,Pais,idProduto,Produto,Custo fabricacao,Unidades Vendidas,Preco venda,Vendas total,Descontos,Dt_ingest,Diferenca_Dias,Diferenca_Meses,Diferenca_Ano
0,2021-04-02,573,1,Moda,636,Alemanha,15,Shorts,10,1178,20,23560,3674.400,2025-08-15,1596,53,4
1,2021-04-02,599,4,Acessórios,637,França,12,Relogio,120,930,15,13950,7795.125,2025-08-15,1596,53,4
2,2021-04-02,1125,1,Moda,636,Alemanha,15,Shorts,10,583,20,11660,3674.400,2025-08-15,1596,53,4
3,2021-04-02,1151,4,Acessórios,637,França,12,Relogio,120,548,15,8220,7795.125,2025-08-15,1596,53,4
4,2021-04-06,394,5,Automitivos,639,USA,8,Limpa vidros,250,503,300,150900,19392.000,2025-08-15,1592,53,4
5,2021-04-06,946,5,Automitivos,639,USA,8,Limpa vidros,250,153,300,45900,19392.000,2025-08-15,1592,53,4
6,2021-04-09,117,5,Automitivos,635,Canadá,10,Pneus,10,195,300,58500,11496.000,2025-08-15,1589,52,4
7,2021-04-09,557,1,Moda,638,México,5,Camiseta,10,61,20,1220,2959.200,2025-08-15,1589,52,4
8,2021-04-09,1109,1,Moda,638,México,5,Camiseta,10,1154,20,23080,2959.200,2025-08-15,1589,52,4
9,2021-04-10,574,1,Moda,637,França,15,Shorts,250,313,7,2191,1252.440,2025-08-15,1588,52,4
10,2021-04-10,690,4,Acessórios,636,Alemanha,2,Braceletes,250,512,15,7680,1107.000,2025-08-15,1588,52,4
11,2021-04-10,1126,1,Moda,637,França,15,Shorts,250,164,7,1148,1252.440,2025-08-15,1588,52,4
12,2021-04-10,1242,4,Acessórios,636,Alemanha,2,Braceletes,250,232,15,3480,1107.000,2025-08-15,1588,52,4
13,2021-04-11,78,3,Eletrônicos,637,França,16,Smartfone,10,1194,125,149250,983.750,2025-08-15,1587,52,4
14,2021-04-12,17,1,Moda,635,Canadá,3,Calça social,10,154,20,3080,0.000,2025-08-15,1586,52,4
15,2021-04-12,208,4,Acessórios,638,México,2,Braceletes,250,947,15,14205,908.400,2025-08-15,1586,52,4
16,2021-04-12,564,1,Moda,639,USA,15,Shorts,250,364,350,127400,41412.000,2025-08-15,1586,52,4
17,2021-04-12,760,4,Acessórios,638,México,2,Braceletes,250,743,15,11145,908.400,2025-08-15,1586,52,4
18,2022-12-30,267,1,Moda,639,USA,15,Shorts,250,701,7,4907,199.500,2025-08-15,959,31,2
19,2022-12-30,819,1,Moda,639,USA,15,Shorts,250,677,7,4739,199.500,2025-08-15,959,31,2

In [18]:
# consolidar dias + meses + anos concatenados
consolidado['Diferenca_Total'] = (
    consolidado['Diferenca_Dias'].astype(str) + ' dias, ' +
    consolidado['Diferenca_Meses'].astype(str) + ' meses, ' +
    consolidado['Diferenca_Ano'].astype(str) + ' anos'
)
consolidado.head(10)

,Data,Id Venda,IdCategoria,Categoria,IdPais,Pais,idProduto,Produto,Custo fabricacao,Unidades Vendidas,Preco venda,Vendas total,Descontos,Dt_ingest,Diferenca_Dias,Diferenca_Meses,Diferenca_Ano,Diferenca_Total
0,2021-04-02,573,1,Moda,636,Alemanha,15,Shorts,10,1178,20,23560,3674.400,2025-08-15,1596,53,4,"1596 dias, 53 meses, 4 anos"
1,2021-04-02,599,4,Acessórios,637,França,12,Relogio,120,930,15,13950,7795.125,2025-08-15,1596,53,4,"1596 dias, 53 meses, 4 anos"
2,2021-04-02,1125,1,Moda,636,Alemanha,15,Shorts,10,583,20,11660,3674.400,2025-08-15,1596,53,4,"1596 dias, 53 meses, 4 anos"
3,2021-04-02,1151,4,Acessórios,637,França,12,Relogio,120,548,15,8220,7795.125,2025-08-15,1596,53,4,"1596 dias, 53 meses, 4 anos"
4,2021-04-06,394,5,Automitivos,639,USA,8,Limpa vidros,250,503,300,150900,19392.000,2025-08-15,1592,53,4,"1592 dias, 53 meses, 4 anos"
5,2021-04-06,946,5,Automitivos,639,USA,8,Limpa vidros,250,153,300,45900,19392.000,2025-08-15,1592,53,4,"1592 dias, 53 meses, 4 anos"
6,2021-04-09,117,5,Automitivos,635,Canadá,10,Pneus,10,195,300,58500,11496.000,2025-08-15,1589,52,4,"1589 dias, 52 meses, 4 anos"
7,2021-04-09,557,1,Moda,638,México,5,Camiseta,10,61,20,1220,2959.200,2025-08-15,1589,52,4,"1589 dias, 52 meses, 4 anos"
8,2021-04-09,1109,1,Moda,638,México,5,Camiseta,10,1154,20,23080,2959.200,2025-08-15,1589,52,4,"1589 dias, 52 meses, 4 anos"
9,2021-04-10,574,1,Moda,637,França,15,Shorts,250,313,7,2191,1252.440,2025-08-15,1588,52,4,"1588 dias, 52 meses, 4 anos"

In [19]:
consolidado.head(10)

,Data,Id Venda,IdCategoria,Categoria,IdPais,Pais,idProduto,Produto,Custo fabricacao,Unidades Vendidas,Preco venda,Vendas total,Descontos,Dt_ingest,Diferenca_Dias,Diferenca_Meses,Diferenca_Ano,Diferenca_Total
0,2021-04-02,573,1,Moda,636,Alemanha,15,Shorts,10,1178,20,23560,3674.400,2025-08-15,1596,53,4,"1596 dias, 53 meses, 4 anos"
1,2021-04-02,599,4,Acessórios,637,França,12,Relogio,120,930,15,13950,7795.125,2025-08-15,1596,53,4,"1596 dias, 53 meses, 4 anos"
2,2021-04-02,1125,1,Moda,636,Alemanha,15,Shorts,10,583,20,11660,3674.400,2025-08-15,1596,53,4,"1596 dias, 53 meses, 4 anos"
3,2021-04-02,1151,4,Acessórios,637,França,12,Relogio,120,548,15,8220,7795.125,2025-08-15,1596,53,4,"1596 dias, 53 meses, 4 anos"
4,2021-04-06,394,5,Automitivos,639,USA,8,Limpa vidros,250,503,300,150900,19392.000,2025-08-15,1592,53,4,"1592 dias, 53 meses, 4 anos"
5,2021-04-06,946,5,Automitivos,639,USA,8,Limpa vidros,250,153,300,45900,19392.000,2025-08-15,1592,53,4,"1592 dias, 53 meses, 4 anos"
6,2021-04-09,117,5,Automitivos,635,Canadá,10,Pneus,10,195,300,58500,11496.000,2025-08-15,1589,52,4,"1589 dias, 52 meses, 4 anos"
7,2021-04-09,557,1,Moda,638,México,5,Camiseta,10,61,20,1220,2959.200,2025-08-15,1589,52,4,"1589 dias, 52 meses, 4 anos"
8,2021-04-09,1109,1,Moda,638,México,5,Camiseta,10,1154,20,23080,2959.200,2025-08-15,1589,52,4,"1589 dias, 52 meses, 4 anos"
9,2021-04-10,574,1,Moda,637,França,15,Shorts,250,313,7,2191,1252.440,2025-08-15,1588,52,4,"1588 dias, 52 meses, 4 anos"

Salvando consolidado em uma pasta especifica Formato Excel

In [20]:
# Caminho da pasta onde estão os arquivos
nome_arquivo = "Dados consolidado Vendas "
caminho_pasta = r"C:\Aplicativos\Meus_Arquivos_Willian\Ambiente_Desenvolvimento\Arquivos_out\Vendas\Consolidado"
# Verifica se a pasta existe, se não existir, cria a pasta
if not os.path.exists(caminho_pasta):
    os.makedirs(caminho_pasta)
# Caminho completo do arquivo de saída
caminho_arquivo_saida = os.path.join(caminho_pasta, f"{nome_arquivo}{Data_Hoje}.xlsx")
# Salva o DataFrame consolidado em um arquivo Excel
consolidado.to_excel(caminho_arquivo_saida, index=False)

In [21]:
#Abrir o diretório onde foi salvo o arquivo
os.startfile(caminho_pasta) # Abrir o diretório onde foi salvo o arquivo
print(f"Arquivo consolidado salvo em: {caminho_arquivo_saida}")
print("Processo de consolidação concluído com sucesso!")

Arquivo consolidado salvo em: C:\Aplicativos\Meus_Arquivos_Willian\Ambiente_Desenvolvimento\Arquivos_out\Vendas\Consolidado\Dados consolidado Vendas 15-08-2025.xlsx
Processo de consolidação concluído com sucesso!

In [22]:
# Lê as configurações do meu computador
import platform
print(f"Sistema Operacional: {platform.system()}")
print(f"Versão do SO: {platform.release()}")
print(f"Arquitetura: {platform.architecture()[0]}")
print(f"Nome do Computador: {platform.node()}")
print(f"Processador: {platform.processor()}")

Sistema Operacional: Windows
Versão do SO: 10
Arquitetura: 64bit
Nome do Computador: willian
Processador: Intel64 Family 6 Model 142 Stepping 12, GenuineIntel

In [23]:
vendas2021_ = pd.read_excel(r"C:\Aplicativos\Meus_Arquivos_Willian\Ambiente_Desenvolvimento\Arquivos_in\Vendas\Vendas2021.xlsx")
vendas2022_ = pd.read_excel(r"C:\Aplicativos\Meus_Arquivos_Willian\Ambiente_Desenvolvimento\Arquivos_in\Vendas\Vendas2022.xlsx")
vendas2023_ = pd.read_excel(r"C:\Aplicativos\Meus_Arquivos_Willian\Ambiente_Desenvolvimento\Arquivos_in\Vendas\Vendas2023.xlsx")

In [24]:
#Mapear manualmente cada arquivos e concatenar manualmente
vendas2021_['Arquivo'] = "Vendas2021.xlsx"
vendas2021_.head(5)

,Data,Id Venda,IdCategoria,Categoria,IdPais,Pais,idProduto,Produto,Custo fabricacao,Unidades Vendidas,Preco venda,Vendas total,Descontos,Arquivo
0,2021-04-02,573,1,Moda,636,Alemanha,15,Shorts,10,1178,20,23560,3674.400,Vendas2021.xlsx
1,2021-04-02,599,4,Acessórios,637,França,12,Relogio,120,930,15,13950,7795.125,Vendas2021.xlsx
2,2021-04-02,1125,1,Moda,636,Alemanha,15,Shorts,10,583,20,11660,3674.400,Vendas2021.xlsx
3,2021-04-02,1151,4,Acessórios,637,França,12,Relogio,120,548,15,8220,7795.125,Vendas2021.xlsx
4,2021-04-06,394,5,Automitivos,639,USA,8,Limpa vidros,250,503,300,150900,19392.000,Vendas2021.xlsx

In [25]:
vendas2022_['Arquivo'] = "Vendas2022.xlsx"
vendas2022_.head(5)

,Data,Id Venda,IdCategoria,Categoria,IdPais,Pais,idProduto,Produto,Custo fabricacao,Unidades Vendidas,Preco venda,Vendas total,Descontos,Arquivo
0,2022-12-30,267,1,Moda,639,USA,15,Shorts,250,701,7,4907,199.5,Vendas2022.xlsx
1,2022-12-30,819,1,Moda,639,USA,15,Shorts,250,677,7,4739,199.5,Vendas2022.xlsx
2,2022-12-29,120,4,Acessórios,639,USA,12,Relogio,10,81,15,1215,577.5,Vendas2022.xlsx
3,2022-12-29,160,3,Eletrônicos,636,Alemanha,9,Notebook,10,481,125,60125,5887.5,Vendas2022.xlsx
4,2022-12-29,712,3,Eletrônicos,636,Alemanha,9,Notebook,10,784,125,98000,5887.5,Vendas2022.xlsx

In [26]:
vendas2023_["Arquivo"] = "Vendas2023.xlsx"
vendas2023_.head(5)

,Data,Id Venda,IdCategoria,Categoria,IdPais,Pais,idProduto,Produto,Custo fabricacao,Unidades Vendidas,Preco venda,Vendas total,Descontos,Arquivo
0,2023-04-02,573,1,Moda,636,Alemanha,15,Shorts,10,1033,20,20660,3674.400,Vendas2023.xlsx
1,2023-04-02,599,4,Acessórios,637,França,12,Relogio,120,739,15,11085,7795.125,Vendas2023.xlsx
2,2023-04-02,1125,1,Moda,636,Alemanha,15,Shorts,10,790,20,15800,3674.400,Vendas2023.xlsx
3,2023-04-02,1151,4,Acessórios,637,França,12,Relogio,120,953,15,14295,7795.125,Vendas2023.xlsx
4,2023-04-06,394,5,Automitivos,639,USA,8,Limpa vidros,250,290,300,87000,19392.000,Vendas2023.xlsx

Empilhar os dados

In [27]:
#Fazendo o empilhamento dos DataFreames
Dados_consolidado = pd.concat([vendas2021_,vendas2022_,vendas2023_], ignore_index=True)
Dados_consolidado.head(100)

,Data,Id Venda,IdCategoria,Categoria,IdPais,Pais,idProduto,Produto,Custo fabricacao,Unidades Vendidas,Preco venda,Vendas total,Descontos,Arquivo
0,2021-04-02,573,1,Moda,636,Alemanha,15,Shorts,10,1178,20,23560,3674.400,Vendas2021.xlsx
1,2021-04-02,599,4,Acessórios,637,França,12,Relogio,120,930,15,13950,7795.125,Vendas2021.xlsx
2,2021-04-02,1125,1,Moda,636,Alemanha,15,Shorts,10,583,20,11660,3674.400,Vendas2021.xlsx
3,2021-04-02,1151,4,Acessórios,637,França,12,Relogio,120,548,15,8220,7795.125,Vendas2021.xlsx
4,2021-04-06,394,5,Automitivos,639,USA,8,Limpa vidros,250,503,300,150900,19392.000,Vendas2021.xlsx
5,2021-04-06,946,5,Automitivos,639,USA,8,Limpa vidros,250,153,300,45900,19392.000,Vendas2021.xlsx
6,2021-04-09,117,5,Automitivos,635,Canadá,10,Pneus,10,195,300,58500,11496.000,Vendas2021.xlsx
7,2021-04-09,557,1,Moda,638,México,5,Camiseta,10,61,20,1220,2959.200,Vendas2021.xlsx
8,2021-04-09,1109,1,Moda,638,México,5,Camiseta,10,1154,20,23080,2959.200,Vendas2021.xlsx
9,2021-04-10,574,1,Moda,637,França,15,Shorts,250,313,7,2191,1252.440,Vendas2021.xlsx
10,2021-04-10,690,4,Acessórios,636,Alemanha,2,Braceletes,250,512,15,7680,1107.000,Vendas2021.xlsx
11,2021-04-10,1126,1,Moda,637,França,15,Shorts,250,164,7,1148,1252.440,Vendas2021.xlsx
12,2021-04-10,1242,4,Acessórios,636,Alemanha,2,Braceletes,250,232,15,3480,1107.000,Vendas2021.xlsx
13,2021-04-11,78,3,Eletrônicos,637,França,16,Smartfone,10,1194,125,149250,983.750,Vendas2021.xlsx
14,2021-04-12,17,1,Moda,635,Canadá,3,Calça social,10,154,20,3080,0.000,Vendas2021.xlsx
15,2021-04-12,208,4,Acessórios,638,México,2,Braceletes,250,947,15,14205,908.400,Vendas2021.xlsx
16,2021-04-12,564,1,Moda,639,USA,15,Shorts,250,364,350,127400,41412.000,Vendas2021.xlsx
17,2021-04-12,760,4,Acessórios,638,México,2,Braceletes,250,743,15,11145,908.400,Vendas2021.xlsx
18,2022-12-30,267,1,Moda,639,USA,15,Shorts,250,701,7,4907,199.500,Vendas2022.xlsx
19,2022-12-30,819,1,Moda,639,USA,15,Shorts,250,677,7,4739,199.500,Vendas2022.xlsx
20,2022-12-29,120,4,Acessórios,639,USA,12,Relogio,10,81,15,1215,577.500,Vendas2022.xlsx
21,2022-12-29,160,3,Eletrônicos,636,Alemanha,9,Notebook,10,481,125,60125,5887.500,Vendas2022.xlsx
22,2022-12-29,712,3,Eletrônicos,636,Alemanha,9,Notebook,10,784,125,98000,5887.500,Vendas2022.xlsx
23,2022-12-28,471,1,Moda,637,França,3,Calça social,120,11,350,3850,22365.000,Vendas2022.xlsx
24,2022-12-28,1023,1,Moda,637,França,3,Calça social,120,1197,350,418950,22365.000,Vendas2022.xlsx
25,2022-12-27,136,1,Moda,639,USA,15,Shorts,250,598,350,209300,1862.000,Vendas2022.xlsx
26,2022-12-27,236,5,Automitivos,638,México,8,Limpa vidros,5,992,300,297600,16500.000,Vendas2022.xlsx
27,2022-12-27,419,2,Calçados,638,México,14,Sapato social,10,959,12,11508,396.360,Vendas2022.xlsx
28,2022-12-27,788,5,Automitivos,638,México,8,Limpa vidros,5,685,300,205500,16500.000,Vendas2022.xlsx
29,2022-12-27,971,2,Calçados,638,México,14,Sapato social,10,341,12,4092,396.360,Vendas2022.xlsx
30,2022-12-25,454,4,Acessórios,635,Canadá,2,Braceletes,260,1079,15,16185,2201.175,Vendas2022.xlsx
31,2022-12-25,1006,4,Acessórios,635,Canadá,2,Braceletes,260,1055,15,15825,2201.175,Vendas2022.xlsx
32,2022-12-20,530,3,Eletrônicos,636,Alemanha,16,Smartfone,260,629,125,78625,43518.750,Vendas2022.xlsx
33,2022-12-20,1082,3,Eletrônicos,636,Alemanha,16,Smartfone,260,1094,125,136750,43518.750,Vendas2022.xlsx
34,2022-12-17,75,4,Acessórios,639,USA,12,Relogio,10,418,15,6270,227.100,Vendas2022.xlsx
35,2022-12-17,145,3,Eletrônicos,637,França,9,Notebook,3,832,125,104000,15913.125,Vendas2022.xlsx
36,2022-12-17,349,1,Moda,636,Alemanha,4,Camisa social,120,665,20,13300,823.200,Vendas2022.xlsx
37,2023-04-02,573,1,Moda,636,Alemanha,15,Shorts,10,1033,20,20660,3674.400,Vendas2023.xlsx
38,2023-04-02,599,4,Acessórios,637,França,12,Relogio,120,739,15,11085,7795.125,Vendas2023.xlsx
39,2023-04-02,1125,1,Moda,636,Alemanha,15,Shorts,10,790,20,15800,3674.400,Vendas2023.xlsx
40,2023-04-02,1151,4,Acessórios,637,França,12,Relogio,120,953,15,14295,7795.125,Vendas2023.xlsx
41,2023-04-06,394,5,Automitivos,639,USA,8,Limpa vidros,250,290,300,87000,19392.000,Vendas2023.xlsx
42,2023-04-06,946,5,Automitivos,639,USA,8,Limpa vidros,250,28,300,8400,19392.000,Vendas2023.xlsx
43,2023-04-09,117,5,Automitivos,635,Canadá,10,Pneus,10,416,300,124800,11496.000,Vendas2023.xlsx
44,2023-04-09,557,1,Moda,638,México,5,Camiseta,10,305,20,6100,2959.200,Vendas2023.xlsx
45,2023-04-09,1109,1,Moda,638,México,5,Camiseta,10,1199,20,23980,2959.200,Vendas2023.xlsx

In [28]:
# É possivel consolidar também passando uma lista de DataFrames
Dados_consolidado_2 = pd.concat([vendas2021_,vendas2022_,vendas2023_],keys=["2021","2022","2023"]) 
Dados_consolidado_2.head(100)

              Data  Id Venda  IdCategoria    Categoria  IdPais      Pais  \
2021 0  2021-04-02       573            1         Moda     636  Alemanha
     1  2021-04-02       599            4   Acessórios     637    França
     2  2021-04-02      1125            1         Moda     636  Alemanha
     3  2021-04-02      1151            4   Acessórios     637    França
     4  2021-04-06       394            5  Automitivos     639       USA
     5  2021-04-06       946            5  Automitivos     639       USA
     6  2021-04-09       117            5  Automitivos     635    Canadá
     7  2021-04-09       557            1         Moda     638    México
     8  2021-04-09      1109            1         Moda     638    México
     9  2021-04-10       574            1         Moda     637    França
     10 2021-04-10       690            4   Acessórios     636  Alemanha
     11 2021-04-10      1126            1         Moda     637    França
     12 2021-04-10      1242            4   Acessórios     636  Alemanha
     13 2021-04-11        78            3  Eletrônicos     637    França
     14 2021-04-12        17            1         Moda     635    Canadá
     15 2021-04-12       208            4   Acessórios     638    México
     16 2021-04-12       564            1         Moda     639       USA
     17 2021-04-12       760            4   Acessórios     638    México
2022 0  2022-12-30       267            1         Moda     639       USA
     1  2022-12-30       819            1         Moda     639       USA
     2  2022-12-29       120            4   Acessórios     639       USA
     3  2022-12-29       160            3  Eletrônicos     636  Alemanha
     4  2022-12-29       712            3  Eletrônicos     636  Alemanha
     5  2022-12-28       471            1         Moda     637    França
     6  2022-12-28      1023            1         Moda     637    França
     7  2022-12-27       136            1         Moda     639       USA
     8  2022-12-27       236            5  Automitivos     638    México
     9  2022-12-27       419            2     Calçados     638    México
     10 2022-12-27       788            5  Automitivos     638    México
     11 2022-12-27       971            2     Calçados     638    México
     12 2022-12-25       454            4   Acessórios     635    Canadá
     13 2022-12-25      1006            4   Acessórios     635    Canadá
     14 2022-12-20       530            3  Eletrônicos     636  Alemanha
     15 2022-12-20      1082            3  Eletrônicos     636  Alemanha
     16 2022-12-17        75            4   Acessórios     639       USA
     17 2022-12-17       145            3  Eletrônicos     637    França
     18 2022-12-17       349            1         Moda     636  Alemanha
2023 0  2023-04-02       573            1         Moda     636  Alemanha
     1  2023-04-02       599            4   Acessórios     637    França
     2  2023-04-02      1125            1         Moda     636  Alemanha
     3  2023-04-02      1151            4   Acessórios     637    França
     4  2023-04-06       394            5  Automitivos     639       USA
     5  2023-04-06       946            5  Automitivos     639       USA
     6  2023-04-09       117            5  Automitivos     635    Canadá
     7  2023-04-09       557            1         Moda     638    México
     8  2023-04-09      1109            1         Moda     638    México

         idProduto        Produto  Custo fabricacao  Unidades Vendidas  \
2021 0          15         Shorts                10               1178
     1          12        Relogio               120                930
     2          15         Shorts                10                583
     3          12        Relogio               120                548
     4           8   Limpa vidros               250                503
     5           8   Limpa vidros               250                153
     6          10          Pneus                10                195
     7           5       Camiseta                10                 61
     8           5       Camiseta                10               1154
     9          15         Shorts               250                313
     10          2     Braceletes               250                512
     11         15         Shorts               250                164
     12          2     Braceletes               250                232
     13         16      Smartfone                10               1194
     14          3   Calça social                10                154
     15          2     Braceletes               250                947
     16         15         Shorts               250                364
     17          2     Braceletes               250                743
2022 0          15         Shorts               250                701
     1          15         Shorts               250                677
     2          12        Relogio                10                 81
     3           9       Notebook                10                481
     4           9       Notebook                10                784
     5           3   Calça social               120                 11
     6           3   Calça social               120               1197
     7          15         Shorts               250                598
     8           8   Limpa vidros                 5                992
     9          14  Sapato social                10                959
     10          8   Limpa vidros                 5                685
     11         14  Sapato social                10                341
     12          2     Braceletes               260               1079
     13          2     Braceletes               260               1055
     14         16      Smartfone               260                629
     15         16      Smartfone               260               1094
     16         12        Relogio                10                418
     17          9       Notebook                 3                832
     18          4  Camisa social               120                665
2023 0          15         Shorts                10               1033
     1          12        Relogio               120                739
     2          15         Shorts                10                790
     3          12        Relogio               120                953
     4           8   Limpa vidros               250                290
     5           8   Limpa vidros               250                 28
     6          10          Pneus                10                416
     7           5       Camiseta                10                305
     8           5       Camiseta                10               1199

         Preco venda  Vendas total  Descontos          Arquivo
2021 0            20         23560   3674.400  Vendas2021.xlsx
     1            15         13950   7795.125  Vendas2021.xlsx
     2            20         11660   3674.400  Vendas2021.xlsx
     3            15          8220   7795.125  Vendas2021.xlsx
     4           300        150900  19392.000  Vendas2021.xlsx
     5           300         45900  19392.000  Vendas2021.xlsx
     6           300         58500  11496.000  Vendas2021.xlsx
     7            20          1220   2959.200  Vendas2021.xlsx
     8            20         23080   2959.200  Vendas2021.xlsx
     9             7          2191   1252.440  Vendas2021.xlsx
     10           15          7680   1107.000  Vendas2021.xlsx
     11            7          1148   1252.440  Vendas2021.xlsx
     12           15          3480   1107.000  Vendas2021.xlsx
     13          125        149250    983.750  Vendas2021.xlsx
     14           20          3080      0.000  Vendas2021.xlsx
     15           15         14205    908.400  Vendas2021.xlsx
     16          350        127400  41412.000  Vendas2021.xlsx
     17           15         11145    908.400  Vendas2021.xlsx
2022 0             7          4907    199.500  Vendas2022.xlsx
     1             7          4739    199.500  Vendas2022.xlsx
     2            15          1215    577.500  Vendas2022.xlsx
     3           125         60125   5887.500  Vendas2022.xlsx
     4           125         98000   5887.500  Vendas2022.xlsx
     5           350          3850  22365.000  Vendas2022.xlsx
     6           350        418950  22365.000  Vendas2022.xlsx
     7           350        209300   1862.000  Vendas2022.xlsx
     8           300        297600  16500.000  Vendas2022.xlsx
     9            12         11508    396.360  Vendas2022.xlsx
     10          300        205500  16500.000  Vendas2022.xlsx
     11           12          4092    396.360  Vendas2022.xlsx
     12           15         16185   2201.175  Vendas2022.xlsx
     13           15         15825   2201.175  Vendas2022.xlsx
     14          125         78625  43518.750  Vendas2022.xlsx
     15          125        136750  43518.750  Vendas2022.xlsx
     16           15          6270    227.100  Vendas2022.xlsx
     17          125        104000  15913.125  Vendas2022.xlsx
     18           20         13300    823.200  Vendas2022.xlsx
2023 0            20         20660   3674.400  Vendas2023.xlsx
     1            15         11085   7795.125  Vendas2023.xlsx
     2            20         15800   3674.400  Vendas2023.xlsx
     3            15         14295   7795.125  Vendas2023.xlsx
     4           300         87000  19392.000  Vendas2023.xlsx
     5           300          8400  19392.000  Vendas2023.xlsx
     6           300        124800  11496.000  Vendas2023.xlsx
     7            20          6100   2959.200  Vendas2023.xlsx
     8            20         23980   2959.200  Vendas2023.xlsx

Verificar se o arquivo existe e adicionar  no final

In [29]:
vendas2021_1 = r"C:\Aplicativos\Meus_Arquivos_Willian\Ambiente_Desenvolvimento\Arquivos_in\Vendas\Vendas2021.xlsx"
vendas2022_2 = r"C:\Aplicativos\Meus_Arquivos_Willian\Ambiente_Desenvolvimento\Arquivos_in\Vendas\Vendas2022.xlsx"
vendas2023_3 = r"C:\Aplicativos\Meus_Arquivos_Willian\Ambiente_Desenvolvimento\Arquivos_in\Vendas\Vendas2023.xlsx"

In [ ]:
#Lendos as variaveis com os caminhos dos arquivos
df2021=pd.read_excel(vendas2021_1)
df2022=pd.read_excel(vendas2022_2)
df2023=pd.read_excel(vendas2023_3)

In [31]:
df2021

,Data,Id Venda,IdCategoria,Categoria,IdPais,Pais,idProduto,Produto,Custo fabricacao,Unidades Vendidas,Preco venda,Vendas total,Descontos
0,2021-04-02,573,1,Moda,636,Alemanha,15,Shorts,10,1178,20,23560,3674.400
1,2021-04-02,599,4,Acessórios,637,França,12,Relogio,120,930,15,13950,7795.125
2,2021-04-02,1125,1,Moda,636,Alemanha,15,Shorts,10,583,20,11660,3674.400
3,2021-04-02,1151,4,Acessórios,637,França,12,Relogio,120,548,15,8220,7795.125
4,2021-04-06,394,5,Automitivos,639,USA,8,Limpa vidros,250,503,300,150900,19392.000
5,2021-04-06,946,5,Automitivos,639,USA,8,Limpa vidros,250,153,300,45900,19392.000
6,2021-04-09,117,5,Automitivos,635,Canadá,10,Pneus,10,195,300,58500,11496.000
7,2021-04-09,557,1,Moda,638,México,5,Camiseta,10,61,20,1220,2959.200
8,2021-04-09,1109,1,Moda,638,México,5,Camiseta,10,1154,20,23080,2959.200
9,2021-04-10,574,1,Moda,637,França,15,Shorts,250,313,7,2191,1252.440
10,2021-04-10,690,4,Acessórios,636,Alemanha,2,Braceletes,250,512,15,7680,1107.000
11,2021-04-10,1126,1,Moda,637,França,15,Shorts,250,164,7,1148,1252.440
12,2021-04-10,1242,4,Acessórios,636,Alemanha,2,Braceletes,250,232,15,3480,1107.000
13,2021-04-11,78,3,Eletrônicos,637,França,16,Smartfone,10,1194,125,149250,983.750
14,2021-04-12,17,1,Moda,635,Canadá,3,Calça social,10,154,20,3080,0.000
15,2021-04-12,208,4,Acessórios,638,México,2,Braceletes,250,947,15,14205,908.400
16,2021-04-12,564,1,Moda,639,USA,15,Shorts,250,364,350,127400,41412.000
17,2021-04-12,760,4,Acessórios,638,México,2,Braceletes,250,743,15,11145,908.400

In [37]:
# Estrair o nome do arquivo sem o caminho e a extensão usando o módulo os
nome_arquivo = os.path.splitext(os.path.basename(vendas2021_1))[0]
nome_arquivo2 = os.path.splitext(os.path.basename(vendas2022_2))[0]
nome_arquivo3 = os.path.splitext(os.path.basename(vendas2023_3))[0]
print(f"Nome do arquivo sem caminho e extensão: {nome_arquivo}")
print(f"Nome do arquivo sem caminho e extensão: {nome_arquivo2}")
print(f"Nome do arquivo sem caminho e extensão: {nome_arquivo3}")

Nome do arquivo sem caminho e extensão: Vendas2021
Nome do arquivo sem caminho e extensão: Vendas2022
Nome do arquivo sem caminho e extensão: Vendas2023

In [38]:
# Adcionar a coluna nome do arquivo
df2021['Arquivo'] = nome_arquivo
df2022['Arquivo'] = nome_arquivo2
df2023['Arquivo'] = nome_arquivo3

In [ ]:
consolidado2 = pd.concat([df2021,df2022,df2023], ignore_index=True)
consolidado2.head(100)

,Data,Id Venda,IdCategoria,Categoria,IdPais,Pais,idProduto,Produto,Custo fabricacao,Unidades Vendidas,Preco venda,Vendas total,Descontos,Arquivo
0,2021-04-02,573,1,Moda,636,Alemanha,15,Shorts,10,1178,20,23560,3674.400,Vendas2021
1,2021-04-02,599,4,Acessórios,637,França,12,Relogio,120,930,15,13950,7795.125,Vendas2021
2,2021-04-02,1125,1,Moda,636,Alemanha,15,Shorts,10,583,20,11660,3674.400,Vendas2021
3,2021-04-02,1151,4,Acessórios,637,França,12,Relogio,120,548,15,8220,7795.125,Vendas2021
4,2021-04-06,394,5,Automitivos,639,USA,8,Limpa vidros,250,503,300,150900,19392.000,Vendas2021
5,2021-04-06,946,5,Automitivos,639,USA,8,Limpa vidros,250,153,300,45900,19392.000,Vendas2021
6,2021-04-09,117,5,Automitivos,635,Canadá,10,Pneus,10,195,300,58500,11496.000,Vendas2021
7,2021-04-09,557,1,Moda,638,México,5,Camiseta,10,61,20,1220,2959.200,Vendas2021
8,2021-04-09,1109,1,Moda,638,México,5,Camiseta,10,1154,20,23080,2959.200,Vendas2021
9,2021-04-10,574,1,Moda,637,França,15,Shorts,250,313,7,2191,1252.440,Vendas2021
10,2021-04-10,690,4,Acessórios,636,Alemanha,2,Braceletes,250,512,15,7680,1107.000,Vendas2021
11,2021-04-10,1126,1,Moda,637,França,15,Shorts,250,164,7,1148,1252.440,Vendas2021
12,2021-04-10,1242,4,Acessórios,636,Alemanha,2,Braceletes,250,232,15,3480,1107.000,Vendas2021
13,2021-04-11,78,3,Eletrônicos,637,França,16,Smartfone,10,1194,125,149250,983.750,Vendas2021
14,2021-04-12,17,1,Moda,635,Canadá,3,Calça social,10,154,20,3080,0.000,Vendas2021
15,2021-04-12,208,4,Acessórios,638,México,2,Braceletes,250,947,15,14205,908.400,Vendas2021
16,2021-04-12,564,1,Moda,639,USA,15,Shorts,250,364,350,127400,41412.000,Vendas2021
17,2021-04-12,760,4,Acessórios,638,México,2,Braceletes,250,743,15,11145,908.400,Vendas2021
18,2022-12-30,267,1,Moda,639,USA,15,Shorts,250,701,7,4907,199.500,Vendas2022
19,2022-12-30,819,1,Moda,639,USA,15,Shorts,250,677,7,4739,199.500,Vendas2022
20,2022-12-29,120,4,Acessórios,639,USA,12,Relogio,10,81,15,1215,577.500,Vendas2022
21,2022-12-29,160,3,Eletrônicos,636,Alemanha,9,Notebook,10,481,125,60125,5887.500,Vendas2022
22,2022-12-29,712,3,Eletrônicos,636,Alemanha,9,Notebook,10,784,125,98000,5887.500,Vendas2022
23,2022-12-28,471,1,Moda,637,França,3,Calça social,120,11,350,3850,22365.000,Vendas2022
24,2022-12-28,1023,1,Moda,637,França,3,Calça social,120,1197,350,418950,22365.000,Vendas2022
25,2022-12-27,136,1,Moda,639,USA,15,Shorts,250,598,350,209300,1862.000,Vendas2022
26,2022-12-27,236,5,Automitivos,638,México,8,Limpa vidros,5,992,300,297600,16500.000,Vendas2022
27,2022-12-27,419,2,Calçados,638,México,14,Sapato social,10,959,12,11508,396.360,Vendas2022
28,2022-12-27,788,5,Automitivos,638,México,8,Limpa vidros,5,685,300,205500,16500.000,Vendas2022
29,2022-12-27,971,2,Calçados,638,México,14,Sapato social,10,341,12,4092,396.360,Vendas2022
30,2022-12-25,454,4,Acessórios,635,Canadá,2,Braceletes,260,1079,15,16185,2201.175,Vendas2022
31,2022-12-25,1006,4,Acessórios,635,Canadá,2,Braceletes,260,1055,15,15825,2201.175,Vendas2022
32,2022-12-20,530,3,Eletrônicos,636,Alemanha,16,Smartfone,260,629,125,78625,43518.750,Vendas2022
33,2022-12-20,1082,3,Eletrônicos,636,Alemanha,16,Smartfone,260,1094,125,136750,43518.750,Vendas2022
34,2022-12-17,75,4,Acessórios,639,USA,12,Relogio,10,418,15,6270,227.100,Vendas2022
35,2022-12-17,145,3,Eletrônicos,637,França,9,Notebook,3,832,125,104000,15913.125,Vendas2022
36,2022-12-17,349,1,Moda,636,Alemanha,4,Camisa social,120,665,20,13300,823.200,Vendas2022
37,2023-04-02,573,1,Moda,636,Alemanha,15,Shorts,10,1033,20,20660,3674.400,Vendas2023
38,2023-04-02,599,4,Acessórios,637,França,12,Relogio,120,739,15,11085,7795.125,Vendas2023
39,2023-04-02,1125,1,Moda,636,Alemanha,15,Shorts,10,790,20,15800,3674.400,Vendas2023
40,2023-04-02,1151,4,Acessórios,637,França,12,Relogio,120,953,15,14295,7795.125,Vendas2023
41,2023-04-06,394,5,Automitivos,639,USA,8,Limpa vidros,250,290,300,87000,19392.000,Vendas2023
42,2023-04-06,946,5,Automitivos,639,USA,8,Limpa vidros,250,28,300,8400,19392.000,Vendas2023
43,2023-04-09,117,5,Automitivos,635,Canadá,10,Pneus,10,416,300,124800,11496.000,Vendas2023
44,2023-04-09,557,1,Moda,638,México,5,Camiseta,10,305,20,6100,2959.200,Vendas2023
45,2023-04-09,1109,1,Moda,638,México,5,Camiseta,10,1199,20,23980,2959.200,Vendas2023