#Consolidando arquivos

In [125]:
import pandas as pd
import os
import time

In [126]:
Data_Hoje = time.strftime("%d-%m-%Y")
print(f"Data de hoje: {Data_Hoje}")

Data de hoje: 27-07-2025

In [127]:
vendas2021 = pd.read_excel(r"C:\Aplicativos\Meus_Arquivos_Willian\Ambiente_Desenvolvimento\Arquivos_in\Vendas\Vendas2021.xlsx")
vendas2022 = pd.read_excel(r"C:\Aplicativos\Meus_Arquivos_Willian\Ambiente_Desenvolvimento\Arquivos_in\Vendas\Vendas2022.xlsx")
vendas2023 = pd.read_excel(r"C:\Aplicativos\Meus_Arquivos_Willian\Ambiente_Desenvolvimento\Arquivos_in\Vendas\Vendas2023.xlsx")

In [128]:
vendas2021.head()

,Data,Id Venda,IdCategoria,Categoria,IdPais,Pais,idProduto,Produto,Custo fabricacao,Unidades Vendidas,Preco venda,Vendas total,Descontos
0,2021-04-02,573,1,Moda,636,Alemanha,15,Shorts,10,1033,20,20660,3674.400
1,2021-04-02,599,4,Acessórios,637,França,12,Relogio,120,739,15,11085,7795.125
2,2021-04-02,1125,1,Moda,636,Alemanha,15,Shorts,10,790,20,15800,3674.400
3,2021-04-02,1151,4,Acessórios,637,França,12,Relogio,120,953,15,14295,7795.125
4,2021-04-06,394,5,Automitivos,639,USA,8,Limpa vidros,250,290,300,87000,19392.000

In [129]:
vendas2022.head()

,Data,Id Venda,IdCategoria,Categoria,IdPais,Pais,idProduto,Produto,Custo fabricacao,Unidades Vendidas,Preco venda,Vendas total,Descontos
0,2022-12-30,267,1,Moda,639,USA,15,Shorts,250,701,7,4907,199.5
1,2022-12-30,819,1,Moda,639,USA,15,Shorts,250,677,7,4739,199.5
2,2022-12-29,120,4,Acessórios,639,USA,12,Relogio,10,81,15,1215,577.5
3,2022-12-29,160,3,Eletrônicos,636,Alemanha,9,Notebook,10,481,125,60125,5887.5
4,2022-12-29,712,3,Eletrônicos,636,Alemanha,9,Notebook,10,784,125,98000,5887.5

In [130]:
vendas2023.head()

,Data,Id Venda,IdCategoria,Categoria,IdPais,Pais,idProduto,Produto,Custo fabricacao,Unidades Vendidas,Preco venda,Vendas total,Descontos
0,2023-04-02,573,1,Moda,636,Alemanha,15,Shorts,10,1033,20,20660,3674.400
1,2023-04-02,599,4,Acessórios,637,França,12,Relogio,120,739,15,11085,7795.125
2,2023-04-02,1125,1,Moda,636,Alemanha,15,Shorts,10,790,20,15800,3674.400
3,2023-04-02,1151,4,Acessórios,637,França,12,Relogio,120,953,15,14295,7795.125
4,2023-04-06,394,5,Automitivos,639,USA,8,Limpa vidros,250,290,300,87000,19392.000

Consolidando arquivos de uma pasta

In [131]:
#Diretório onde estão os arquivos
diretorio = r"C:\Aplicativos\Meus_Arquivos_Willian\Ambiente_Desenvolvimento\Arquivos_in\Vendas"

#Lista os arquivos do diretório
arquivos = []

#Iterar sobre os arquivos no diretório
for arquivo in os.listdir(diretorio):                        #lista os arquivos no diretório
    if arquivo.endswith(".xlsx"):                            #Verifica se o arquivo é um Excel
        caminho_completo = os.path.join(diretorio, arquivo)  #Cria o caminho completo do arquivo
        df = pd.read_excel(caminho_completo)                 #Lê o arquivo Excel
        arquivos.append(df)                                  #Adiciona o DataFrame à lista 1 a 1
#Consolidar os DataFrames em um único DataFrame
consolidado = pd.concat(arquivos, ignore_index=True)
consolidado.head(20)

,Data,Id Venda,IdCategoria,Categoria,IdPais,Pais,idProduto,Produto,Custo fabricacao,Unidades Vendidas,Preco venda,Vendas total,Descontos
0,2021-04-02,573,1,Moda,636,Alemanha,15,Shorts,10,1033,20,20660,3674.400
1,2021-04-02,599,4,Acessórios,637,França,12,Relogio,120,739,15,11085,7795.125
2,2021-04-02,1125,1,Moda,636,Alemanha,15,Shorts,10,790,20,15800,3674.400
3,2021-04-02,1151,4,Acessórios,637,França,12,Relogio,120,953,15,14295,7795.125
4,2021-04-06,394,5,Automitivos,639,USA,8,Limpa vidros,250,290,300,87000,19392.000
5,2021-04-06,946,5,Automitivos,639,USA,8,Limpa vidros,250,28,300,8400,19392.000
6,2021-04-09,117,5,Automitivos,635,Canadá,10,Pneus,10,416,300,124800,11496.000
7,2021-04-09,557,1,Moda,638,México,5,Camiseta,10,305,20,6100,2959.200
8,2021-04-09,1109,1,Moda,638,México,5,Camiseta,10,1199,20,23980,2959.200
9,2021-04-10,574,1,Moda,637,França,15,Shorts,250,470,7,3290,1252.440
10,2021-04-10,690,4,Acessórios,636,Alemanha,2,Braceletes,250,656,15,9840,1107.000
11,2021-04-10,1126,1,Moda,637,França,15,Shorts,250,595,7,4165,1252.440
12,2021-04-10,1242,4,Acessórios,636,Alemanha,2,Braceletes,250,805,15,12075,1107.000
13,2021-04-11,78,3,Eletrônicos,637,França,16,Smartfone,10,549,125,68625,983.750
14,2021-04-12,17,1,Moda,635,Canadá,3,Calça social,10,1061,20,21220,0.000
15,2021-04-12,208,4,Acessórios,638,México,2,Braceletes,250,500,15,7500,908.400
16,2021-04-12,564,1,Moda,639,USA,15,Shorts,250,409,350,143150,41412.000
17,2021-04-12,760,4,Acessórios,638,México,2,Braceletes,250,1145,15,17175,908.400
18,2022-12-30,267,1,Moda,639,USA,15,Shorts,250,701,7,4907,199.500
19,2022-12-30,819,1,Moda,639,USA,15,Shorts,250,677,7,4739,199.500

In [132]:
#Colacar a data de hoje no arquivo consolidado
consolidado['Dt_ingest'] = Data_Hoje
consolidado.head(20)

,Data,Id Venda,IdCategoria,Categoria,IdPais,Pais,idProduto,Produto,Custo fabricacao,Unidades Vendidas,Preco venda,Vendas total,Descontos,Dt_ingest
0,2021-04-02,573,1,Moda,636,Alemanha,15,Shorts,10,1033,20,20660,3674.400,27-07-2025
1,2021-04-02,599,4,Acessórios,637,França,12,Relogio,120,739,15,11085,7795.125,27-07-2025
2,2021-04-02,1125,1,Moda,636,Alemanha,15,Shorts,10,790,20,15800,3674.400,27-07-2025
3,2021-04-02,1151,4,Acessórios,637,França,12,Relogio,120,953,15,14295,7795.125,27-07-2025
4,2021-04-06,394,5,Automitivos,639,USA,8,Limpa vidros,250,290,300,87000,19392.000,27-07-2025
5,2021-04-06,946,5,Automitivos,639,USA,8,Limpa vidros,250,28,300,8400,19392.000,27-07-2025
6,2021-04-09,117,5,Automitivos,635,Canadá,10,Pneus,10,416,300,124800,11496.000,27-07-2025
7,2021-04-09,557,1,Moda,638,México,5,Camiseta,10,305,20,6100,2959.200,27-07-2025
8,2021-04-09,1109,1,Moda,638,México,5,Camiseta,10,1199,20,23980,2959.200,27-07-2025
9,2021-04-10,574,1,Moda,637,França,15,Shorts,250,470,7,3290,1252.440,27-07-2025
10,2021-04-10,690,4,Acessórios,636,Alemanha,2,Braceletes,250,656,15,9840,1107.000,27-07-2025
11,2021-04-10,1126,1,Moda,637,França,15,Shorts,250,595,7,4165,1252.440,27-07-2025
12,2021-04-10,1242,4,Acessórios,636,Alemanha,2,Braceletes,250,805,15,12075,1107.000,27-07-2025
13,2021-04-11,78,3,Eletrônicos,637,França,16,Smartfone,10,549,125,68625,983.750,27-07-2025
14,2021-04-12,17,1,Moda,635,Canadá,3,Calça social,10,1061,20,21220,0.000,27-07-2025
15,2021-04-12,208,4,Acessórios,638,México,2,Braceletes,250,500,15,7500,908.400,27-07-2025
16,2021-04-12,564,1,Moda,639,USA,15,Shorts,250,409,350,143150,41412.000,27-07-2025
17,2021-04-12,760,4,Acessórios,638,México,2,Braceletes,250,1145,15,17175,908.400,27-07-2025
18,2022-12-30,267,1,Moda,639,USA,15,Shorts,250,701,7,4907,199.500,27-07-2025
19,2022-12-30,819,1,Moda,639,USA,15,Shorts,250,677,7,4739,199.500,27-07-2025

In [133]:
#Converte as data para formato de data
consolidado['Dt_ingest'] = pd.to_datetime(consolidado['Dt_ingest'], format='%d-%m-%Y')
consolidado['Data'] = pd.to_datetime(consolidado['Data'], format='%d-%m-%Y')

In [134]:
#Subtrrair Dt_ingest da Data ver os dias de diferença
consolidado['Diferenca_Dias'] = (consolidado['Dt_ingest'] - consolidado['Data']).dt.days

In [135]:
consolidado.head(20)

,Data,Id Venda,IdCategoria,Categoria,IdPais,Pais,idProduto,Produto,Custo fabricacao,Unidades Vendidas,Preco venda,Vendas total,Descontos,Dt_ingest,Diferenca_Dias
0,2021-04-02,573,1,Moda,636,Alemanha,15,Shorts,10,1033,20,20660,3674.400,2025-07-27,1577
1,2021-04-02,599,4,Acessórios,637,França,12,Relogio,120,739,15,11085,7795.125,2025-07-27,1577
2,2021-04-02,1125,1,Moda,636,Alemanha,15,Shorts,10,790,20,15800,3674.400,2025-07-27,1577
3,2021-04-02,1151,4,Acessórios,637,França,12,Relogio,120,953,15,14295,7795.125,2025-07-27,1577
4,2021-04-06,394,5,Automitivos,639,USA,8,Limpa vidros,250,290,300,87000,19392.000,2025-07-27,1573
5,2021-04-06,946,5,Automitivos,639,USA,8,Limpa vidros,250,28,300,8400,19392.000,2025-07-27,1573
6,2021-04-09,117,5,Automitivos,635,Canadá,10,Pneus,10,416,300,124800,11496.000,2025-07-27,1570
7,2021-04-09,557,1,Moda,638,México,5,Camiseta,10,305,20,6100,2959.200,2025-07-27,1570
8,2021-04-09,1109,1,Moda,638,México,5,Camiseta,10,1199,20,23980,2959.200,2025-07-27,1570
9,2021-04-10,574,1,Moda,637,França,15,Shorts,250,470,7,3290,1252.440,2025-07-27,1569
10,2021-04-10,690,4,Acessórios,636,Alemanha,2,Braceletes,250,656,15,9840,1107.000,2025-07-27,1569
11,2021-04-10,1126,1,Moda,637,França,15,Shorts,250,595,7,4165,1252.440,2025-07-27,1569
12,2021-04-10,1242,4,Acessórios,636,Alemanha,2,Braceletes,250,805,15,12075,1107.000,2025-07-27,1569
13,2021-04-11,78,3,Eletrônicos,637,França,16,Smartfone,10,549,125,68625,983.750,2025-07-27,1568
14,2021-04-12,17,1,Moda,635,Canadá,3,Calça social,10,1061,20,21220,0.000,2025-07-27,1567
15,2021-04-12,208,4,Acessórios,638,México,2,Braceletes,250,500,15,7500,908.400,2025-07-27,1567
16,2021-04-12,564,1,Moda,639,USA,15,Shorts,250,409,350,143150,41412.000,2025-07-27,1567
17,2021-04-12,760,4,Acessórios,638,México,2,Braceletes,250,1145,15,17175,908.400,2025-07-27,1567
18,2022-12-30,267,1,Moda,639,USA,15,Shorts,250,701,7,4907,199.500,2025-07-27,940
19,2022-12-30,819,1,Moda,639,USA,15,Shorts,250,677,7,4739,199.500,2025-07-27,940

In [136]:
# ver a diferença em meses
consolidado['Diferenca_Meses'] = (consolidado['Dt_ingest'] - consolidado['Data']).dt.days // 30

In [137]:
consolidado.head(20)

,Data,Id Venda,IdCategoria,Categoria,IdPais,Pais,idProduto,Produto,Custo fabricacao,Unidades Vendidas,Preco venda,Vendas total,Descontos,Dt_ingest,Diferenca_Dias,Diferenca_Meses
0,2021-04-02,573,1,Moda,636,Alemanha,15,Shorts,10,1033,20,20660,3674.400,2025-07-27,1577,52
1,2021-04-02,599,4,Acessórios,637,França,12,Relogio,120,739,15,11085,7795.125,2025-07-27,1577,52
2,2021-04-02,1125,1,Moda,636,Alemanha,15,Shorts,10,790,20,15800,3674.400,2025-07-27,1577,52
3,2021-04-02,1151,4,Acessórios,637,França,12,Relogio,120,953,15,14295,7795.125,2025-07-27,1577,52
4,2021-04-06,394,5,Automitivos,639,USA,8,Limpa vidros,250,290,300,87000,19392.000,2025-07-27,1573,52
5,2021-04-06,946,5,Automitivos,639,USA,8,Limpa vidros,250,28,300,8400,19392.000,2025-07-27,1573,52
6,2021-04-09,117,5,Automitivos,635,Canadá,10,Pneus,10,416,300,124800,11496.000,2025-07-27,1570,52
7,2021-04-09,557,1,Moda,638,México,5,Camiseta,10,305,20,6100,2959.200,2025-07-27,1570,52
8,2021-04-09,1109,1,Moda,638,México,5,Camiseta,10,1199,20,23980,2959.200,2025-07-27,1570,52
9,2021-04-10,574,1,Moda,637,França,15,Shorts,250,470,7,3290,1252.440,2025-07-27,1569,52
10,2021-04-10,690,4,Acessórios,636,Alemanha,2,Braceletes,250,656,15,9840,1107.000,2025-07-27,1569,52
11,2021-04-10,1126,1,Moda,637,França,15,Shorts,250,595,7,4165,1252.440,2025-07-27,1569,52
12,2021-04-10,1242,4,Acessórios,636,Alemanha,2,Braceletes,250,805,15,12075,1107.000,2025-07-27,1569,52
13,2021-04-11,78,3,Eletrônicos,637,França,16,Smartfone,10,549,125,68625,983.750,2025-07-27,1568,52
14,2021-04-12,17,1,Moda,635,Canadá,3,Calça social,10,1061,20,21220,0.000,2025-07-27,1567,52
15,2021-04-12,208,4,Acessórios,638,México,2,Braceletes,250,500,15,7500,908.400,2025-07-27,1567,52
16,2021-04-12,564,1,Moda,639,USA,15,Shorts,250,409,350,143150,41412.000,2025-07-27,1567,52
17,2021-04-12,760,4,Acessórios,638,México,2,Braceletes,250,1145,15,17175,908.400,2025-07-27,1567,52
18,2022-12-30,267,1,Moda,639,USA,15,Shorts,250,701,7,4907,199.500,2025-07-27,940,31
19,2022-12-30,819,1,Moda,639,USA,15,Shorts,250,677,7,4739,199.500,2025-07-27,940,31

In [138]:
#ver a diferença em anos
consolidado['Diferenca_Ano'] = (consolidado['Dt_ingest'] - consolidado['Data']).dt.days // 365

In [139]:
consolidado.head(20)

,Data,Id Venda,IdCategoria,Categoria,IdPais,Pais,idProduto,Produto,Custo fabricacao,Unidades Vendidas,Preco venda,Vendas total,Descontos,Dt_ingest,Diferenca_Dias,Diferenca_Meses,Diferenca_Ano
0,2021-04-02,573,1,Moda,636,Alemanha,15,Shorts,10,1033,20,20660,3674.400,2025-07-27,1577,52,4
1,2021-04-02,599,4,Acessórios,637,França,12,Relogio,120,739,15,11085,7795.125,2025-07-27,1577,52,4
2,2021-04-02,1125,1,Moda,636,Alemanha,15,Shorts,10,790,20,15800,3674.400,2025-07-27,1577,52,4
3,2021-04-02,1151,4,Acessórios,637,França,12,Relogio,120,953,15,14295,7795.125,2025-07-27,1577,52,4
4,2021-04-06,394,5,Automitivos,639,USA,8,Limpa vidros,250,290,300,87000,19392.000,2025-07-27,1573,52,4
5,2021-04-06,946,5,Automitivos,639,USA,8,Limpa vidros,250,28,300,8400,19392.000,2025-07-27,1573,52,4
6,2021-04-09,117,5,Automitivos,635,Canadá,10,Pneus,10,416,300,124800,11496.000,2025-07-27,1570,52,4
7,2021-04-09,557,1,Moda,638,México,5,Camiseta,10,305,20,6100,2959.200,2025-07-27,1570,52,4
8,2021-04-09,1109,1,Moda,638,México,5,Camiseta,10,1199,20,23980,2959.200,2025-07-27,1570,52,4
9,2021-04-10,574,1,Moda,637,França,15,Shorts,250,470,7,3290,1252.440,2025-07-27,1569,52,4
10,2021-04-10,690,4,Acessórios,636,Alemanha,2,Braceletes,250,656,15,9840,1107.000,2025-07-27,1569,52,4
11,2021-04-10,1126,1,Moda,637,França,15,Shorts,250,595,7,4165,1252.440,2025-07-27,1569,52,4
12,2021-04-10,1242,4,Acessórios,636,Alemanha,2,Braceletes,250,805,15,12075,1107.000,2025-07-27,1569,52,4
13,2021-04-11,78,3,Eletrônicos,637,França,16,Smartfone,10,549,125,68625,983.750,2025-07-27,1568,52,4
14,2021-04-12,17,1,Moda,635,Canadá,3,Calça social,10,1061,20,21220,0.000,2025-07-27,1567,52,4
15,2021-04-12,208,4,Acessórios,638,México,2,Braceletes,250,500,15,7500,908.400,2025-07-27,1567,52,4
16,2021-04-12,564,1,Moda,639,USA,15,Shorts,250,409,350,143150,41412.000,2025-07-27,1567,52,4
17,2021-04-12,760,4,Acessórios,638,México,2,Braceletes,250,1145,15,17175,908.400,2025-07-27,1567,52,4
18,2022-12-30,267,1,Moda,639,USA,15,Shorts,250,701,7,4907,199.500,2025-07-27,940,31,2
19,2022-12-30,819,1,Moda,639,USA,15,Shorts,250,677,7,4739,199.500,2025-07-27,940,31,2

In [140]:
# consolidar dias + meses + anos concatenados
consolidado['Diferenca_Total'] = (
    consolidado['Diferenca_Dias'].astype(str) + ' dias, ' +
    consolidado['Diferenca_Meses'].astype(str) + ' meses, ' +
    consolidado['Diferenca_Ano'].astype(str) + ' anos'
)
consolidado.head(10)

,Data,Id Venda,IdCategoria,Categoria,IdPais,Pais,idProduto,Produto,Custo fabricacao,Unidades Vendidas,Preco venda,Vendas total,Descontos,Dt_ingest,Diferenca_Dias,Diferenca_Meses,Diferenca_Ano,Diferenca_Total
0,2021-04-02,573,1,Moda,636,Alemanha,15,Shorts,10,1033,20,20660,3674.400,2025-07-27,1577,52,4,"1577 dias, 52 meses, 4 anos"
1,2021-04-02,599,4,Acessórios,637,França,12,Relogio,120,739,15,11085,7795.125,2025-07-27,1577,52,4,"1577 dias, 52 meses, 4 anos"
2,2021-04-02,1125,1,Moda,636,Alemanha,15,Shorts,10,790,20,15800,3674.400,2025-07-27,1577,52,4,"1577 dias, 52 meses, 4 anos"
3,2021-04-02,1151,4,Acessórios,637,França,12,Relogio,120,953,15,14295,7795.125,2025-07-27,1577,52,4,"1577 dias, 52 meses, 4 anos"
4,2021-04-06,394,5,Automitivos,639,USA,8,Limpa vidros,250,290,300,87000,19392.000,2025-07-27,1573,52,4,"1573 dias, 52 meses, 4 anos"
5,2021-04-06,946,5,Automitivos,639,USA,8,Limpa vidros,250,28,300,8400,19392.000,2025-07-27,1573,52,4,"1573 dias, 52 meses, 4 anos"
6,2021-04-09,117,5,Automitivos,635,Canadá,10,Pneus,10,416,300,124800,11496.000,2025-07-27,1570,52,4,"1570 dias, 52 meses, 4 anos"
7,2021-04-09,557,1,Moda,638,México,5,Camiseta,10,305,20,6100,2959.200,2025-07-27,1570,52,4,"1570 dias, 52 meses, 4 anos"
8,2021-04-09,1109,1,Moda,638,México,5,Camiseta,10,1199,20,23980,2959.200,2025-07-27,1570,52,4,"1570 dias, 52 meses, 4 anos"
9,2021-04-10,574,1,Moda,637,França,15,Shorts,250,470,7,3290,1252.440,2025-07-27,1569,52,4,"1569 dias, 52 meses, 4 anos"

Salvando consolidado em uma pasta especifica Formato Excel

In [141]:
# Caminho da pasta onde estão os arquivos
nome_arquivo = "Dados consolidado Vendas "
caminho_pasta = r"C:\Aplicativos\Meus_Arquivos_Willian\Ambiente_Desenvolvimento\Arquivos_out\Vendas\Consolidado"
# Verifica se a pasta existe, se não existir, cria a pasta
if not os.path.exists(caminho_pasta):
    os.makedirs(caminho_pasta)
# Caminho completo do arquivo de saída
caminho_arquivo_saida = os.path.join(caminho_pasta, f"{nome_arquivo}{Data_Hoje}.xlsx")
# Salva o DataFrame consolidado em um arquivo Excel
consolidado.to_excel(caminho_arquivo_saida, index=False)

In [142]:
#Abrir o diretório onde foi salvo o arquivo
os.startfile(caminho_pasta) # Abrir o diretório onde foi salvo o arquivo
print(f"Arquivo consolidado salvo em: {caminho_arquivo_saida}")
print("Processo de consolidação concluído com sucesso!")

Arquivo consolidado salvo em: C:\Aplicativos\Meus_Arquivos_Willian\Ambiente_Desenvolvimento\Arquivos_out\Vendas\Consolidado\Dados consolidado Vendas 27-07-2025.xlsx
Processo de consolidação concluído com sucesso!

In [146]:
# Lê as configurações do meu computador
import platform
print(f"Sistema Operacional: {platform.system()}")
print(f"Versão do SO: {platform.release()}")
print(f"Arquitetura: {platform.architecture()[0]}")
print(f"Nome do Computador: {platform.node()}")
print(f"Processador: {platform.processor()}")

Sistema Operacional: Windows
Versão do SO: 10
Arquitetura: 64bit
Nome do Computador: willian
Processador: Intel64 Family 6 Model 142 Stepping 12, GenuineIntel